server:
   # Eureka 服务器的默认端口是：8761
   port: 9000
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka


spring:
   application:
      #定义应用名
      name: flower-config
   cloud:
     config:
        server:
          git:
            default-label: main
            uri: https://github.com/chun-wlsl/repo1/
            search-paths: /C89-S3-Pwl
            username:
            password:
      